version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=<YOUR_TAILSCALE_IP>
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Europe/Copenhagen
      - WEBHOOK_URL=<YOUR_CLOUDFLARE_TUNNEL_URL>
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./backups:/backups

volumes:
  n8n_data:
